name: "Lint PR"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        with:
          requireScope: false
          subjectPattern: ^(?![A-Z]).+$
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
